export const REDIS_HOST = 'REDIS_HOST';
export const REDIS_PORT = 'REDIS_PORT';
export const REDIS_CONNECTION_TIMEOUT = 'REDIS_CONNECTION_TIMEOUT';
export const REDIS_NO_DELAY = 'REDIS_NO_DELAY';
export const REDIS_KEEP_ALIVE = 'REDIS_KEEP_ALIVE';
export const REDIS_USERNAME = 'REDIS_USERNAME';
export const REDIS_PASSWORD = 'REDIS_PASSWORD';
export const REDIS_NAME = 'REDIS_NAME';
export const REDIS_DATABASE = 'REDIS_DATABASE';
export const REDIS_COMMANDS_QUEUE_MAX_LENGTH =
	'REDIS_COMMANDS_QUEUE_MAX_LENGTH';
export const REDIS_DISABLE_OFFLINE_QUEUE = 'REDIS_DISABLE_OFFLINE_QUEUE';
export const REDIS_READONLY = 'REDIS_READONLY';
export const REDIS_LEGACY_MODE = 'REDIS_LEGACY_MODE';
export const REDIS_ISOLATION_POOL_OPTIONS = 'REDIS_ISOLATION_POOL_OPTIONS';
export const REDIS_PING_INTERVAL = 'REDIS_PING_INTERVAL';
export const REDIS_DISABLE_CLIENT_INFO = 'REDIS_DISABLE_CLIENT_INFO';
export const REDIS_CLIENT_INFO_TAG = 'REDIS_CLIENT_INFO_TAG';
